# NumPy

## Arrays

In [1]:
# N dimensional arrays (one dimensional vector, 2D matrix)
# Random number capability, statistical distribution

In [2]:
import numpy as np

In [3]:
a = [1,2,3]
type(a)

list

In [4]:
# To see functions related to numpy after "np." press tab

In [5]:
# changing type
b = np.array(a)

In [6]:
type(b)

numpy.ndarray

In [7]:
np.array(range(0,10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10)
# same as above code line, function to create array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.linspace(0,5,6)
# The ditance between numbers generated will be equal
# Equally spaced from 0 to 5 will include 6 numbers
# (start point , till what number you want , how many number between this you want)

array([0., 1., 2., 3., 4., 5.])

In [10]:
np.linspace(0,3,31)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. ])

In [11]:
# 2D array = List(List)
c = [[1,2,3],[10,20,30]]
np.array(c)

array([[ 1,  2,  3],
       [10, 20, 30]])

In [12]:
np.zeros(5)
# 1D

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,5))
# Multidimensional by tuple, 3 rows X 5 columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
first_ten = np.arange(0,10)
first_ten

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
first_ten[3]

np.int64(3)

In [16]:
# Slicing and Dicing
# [Start from this index (including), End is excluded, ]

In [17]:
first_ten[3:5]

array([3, 4])

In [18]:
first_ten[:2]

array([0, 1])

In [19]:
first_ten[6:]

array([6, 7, 8, 9])

In [20]:
first_thirty = np.linspace(0,29,30)
three_by_ten = first_thirty.reshape(3,10)
three_by_ten

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.]])

In [21]:
three_by_ten.shape

(3, 10)

## Operations in NumPy

In [22]:
first_ten + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [23]:
first_ten - 10

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [24]:
first_ten + first_ten

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
first_ten * first_ten

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [26]:
# Change element
first_ten[0] = 10
first_ten

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [27]:
# Set all elements to 10 by giving no range in slicing
first_ten[:] = 10

In [28]:
first_ten
print (first_ten)

[10 10 10 10 10 10 10 10 10 10]


In [29]:
first_ten = np.arange(0,10)
first_five = first_ten[0:5]

In [30]:
first_ten
first_five

array([0, 1, 2, 3, 4])

In [31]:
# Broadcasting done changes to all
first_five[:] = 0
first_five

array([0, 0, 0, 0, 0])

In [32]:
first_ten

array([0, 0, 0, 0, 0, 5, 6, 7, 8, 9])

# Pandas

In [33]:
import pandas as pd

In [34]:
mydays = ['Sun','Mon','Tue']
myexp = [34,44,29] # expenses

In [35]:
type(myexp)

list

In [36]:
a_mydays = np.array(mydays)
a_myexp = np.array(myexp)

In [37]:
type(a_myexp)
a_myexp 

array([34, 44, 29])

In [38]:
pd.Series(a_myexp)

0    34
1    44
2    29
dtype: int64

In [39]:
pd.Series(myexp)

0    34
1    44
2    29
dtype: int64

In [40]:
pd.Series(a_myexp,a_mydays)

Sun    34
Mon    44
Tue    29
dtype: int64

In [41]:
s_myexp = pd.Series(data = a_myexp, index = a_mydays)
s_myexp

Sun    34
Mon    44
Tue    29
dtype: int64

In [42]:
# Pandas array is better than NumPy as it has actual look and feel, with data displayed as rows and coloumns

In [43]:
# My expense on Monday
a_myexp[0]

np.int64(34)

# Pandas Dataframe

In [44]:
my_nums = np.arange(1,10)
my_nums

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
# 1D array to 3X3 matrix
my_nums = np.reshape(my_nums, (3, 3))
my_nums

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
pd.DataFrame(my_nums) # rows and coloumns format with index

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [47]:
my_index = ['Row 1','Row 2','Row 3']
my_col = ['Col 1','Col 2','Col 3']

In [48]:
df = pd.DataFrame(data = my_nums, index = my_index, columns = my_col)
df

Col 1  Col 2  Col 3
Row 1      1      2      3
Row 2      4      5      6
Row 3      7      8      9

In [49]:
pd.DataFrame({'A': [1,2,3], 'B' : [4,5,6], 'index' : [7,8,9]})

A  B  index
0  1  4      7
1  2  5      8
2  3  6      9