#### Predicting flower species

In [1]:
from sklearn import datasets
import pandas as pd
import numpy as np

In [2]:
iris = datasets.load_iris()
type(iris)

sklearn.utils._bunch.Bunch

In [3]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [4]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
x = iris.data # input variables
y = iris.target

In [8]:
#split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4, random_state=123)

In [9]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=8)
#assume k = 8

knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=8)

In [10]:
y_pred = knn.predict(x_test)
#predict the labels on the test data

In [11]:
y_pred

array([1, 2, 2, 1, 0, 1, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 0, 2,
       0, 1, 0, 0, 0, 1, 2, 0, 2, 2, 0, 0, 1, 1, 2, 0, 0, 1, 1, 0, 2, 2,
       2, 2, 2, 1, 0, 0, 2, 0, 0, 1, 1, 1, 1, 2, 1, 2])

In [12]:
y_test

array([1, 2, 2, 1, 0, 2, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 0, 2,
       0, 2, 0, 0, 0, 2, 2, 0, 2, 2, 0, 0, 1, 1, 2, 0, 0, 1, 1, 0, 2, 2,
       2, 2, 2, 1, 0, 0, 2, 0, 0, 1, 1, 1, 1, 2, 1, 2])

In [13]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix


print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

[[22  0  0]
 [ 0 16  0]
 [ 0  3 19]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        22
           1       0.84      1.00      0.91        16
           2       1.00      0.86      0.93        22

    accuracy                           0.95        60
   macro avg       0.95      0.95      0.95        60
weighted avg       0.96      0.95      0.95        60



-Support is No. of observations in test data

-In matrix each column sum represents Predicted values 

-Rows are Actual values

-Diagonals (True Positives) in matrix represents No. of correct predictions for each label 

-Recall(Hit Ratio) = Individual level accuracy (%), that all actual values were correctly predicted (quantity, row wise)

-Precision = Proportion (%) of predictions made which are actually correct in each label (quality, column wise)

-f1-score = harmonic mean of Precision or Recall

In [14]:
y_pred_train = knn.predict(x_train)
#predict the labels on the test data

In [15]:
print(confusion_matrix(y_train, y_pred_train))

print(classification_report(y_train, y_pred_train))

[[28  0  0]
 [ 0 33  1]
 [ 0  2 26]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        28
           1       0.94      0.97      0.96        34
           2       0.96      0.93      0.95        28

    accuracy                           0.97        90
   macro avg       0.97      0.97      0.97        90
weighted avg       0.97      0.97      0.97        90



**Tune and Optimize KNN in python using scikit-learn**

In [16]:

from sklearn.model_selection import GridSearchCV

parameters = {"n_neighbors": range(1, 50)} # range given end is not included (till 49)

gridsearch = GridSearchCV(KNeighborsClassifier(), parameters, cv=5)

gridsearch.fit(x_train, y_train)

# fitting on trained data 


GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': range(1, 50)})

In [17]:
gridsearch.best_params_

{'n_neighbors': 3}

In [18]:
# now use this grid search model to further use on test data, no need to repeat the process
y_pred = gridsearch.predict(x_test)
#n_neighbors=3

In [19]:
print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

[[22  0  0]
 [ 0 15  1]
 [ 0  1 21]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        22
           1       0.94      0.94      0.94        16
           2       0.95      0.95      0.95        22

    accuracy                           0.97        60
   macro avg       0.96      0.96      0.96        60
weighted avg       0.97      0.97      0.97        60



In [20]:
# Checking overfitting on train data
y_predtrain = gridsearch.predict(x_train)
#n_neighbors=3
print(classification_report(y_train, y_predtrain))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        28
           1       0.94      0.97      0.96        34
           2       0.96      0.93      0.95        28

    accuracy                           0.97        90
   macro avg       0.97      0.97      0.97        90
weighted avg       0.97      0.97      0.97        90



97% accuracy with uniform weightage model

In [21]:
# Tuning model for prefferential weightage
parameters={'n_neighbors': range(1, 50),
                         'weights': ['uniform', 'distance']}
GD = GridSearchCV(KNeighborsClassifier(),parameters,cv=5)
# default options --> uniform (all points in the neighborhood are weighted equally)
# another option --> distance (weights closer neighbors more heavily than farther neighbors)

In [22]:
GD.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': range(1, 50),
                         'weights': ['uniform', 'distance']})

In [23]:
# according to this we are getting better at 6 n neighbors above was 3 for equal weightage
y_pred = GD.predict(x_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        22
           1       1.00      0.94      0.97        16
           2       0.96      1.00      0.98        22

    accuracy                           0.98        60
   macro avg       0.99      0.98      0.98        60
weighted avg       0.98      0.98      0.98        60



In [24]:
# To check overfitting 
y_predtrain = GD.predict(x_train)
print(classification_report(y_train, y_predtrain))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        28
           1       1.00      1.00      1.00        34
           2       1.00      1.00      1.00        28

    accuracy                           1.00        90
   macro avg       1.00      1.00      1.00        90
weighted avg       1.00      1.00      1.00        90



Now as it is overfitted, we wont consider prefferential weightage.

### KNN with PCA


In [25]:
#standariztion process: using standard scaler
#scikit learn prime package: machine learning: sklearn
from sklearn.preprocessing import StandardScaler

#instantiate the standard scaler: create an instance
scaler = StandardScaler(copy=True, with_mean=True, with_std=True)

#fittng the scaler on data
#scaler.fit(df)#algo will apply all the required maths; mean and stdev of each variable

#samples_scaled = scaler.transform(df)
#result of the scaler is always in array form

samples_scaled = scaler.fit_transform(x)
print(samples_scaled)
print()
print(x)

[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

In [26]:
# Import PCA
from sklearn.decomposition import PCA

# Create PCA instance: model
model = PCA() #all pcs will be used

# Apply the fit_transform method of model to grains: pca_features
x = model.fit_transform(samples_scaled)

#principal components or PCA features
x.shape

(150, 4)

In [27]:
# Now seeing how much variation explained by PCs
import numpy as np

print(np.round(model.explained_variance_ratio_ * 100, 1))

[73.  22.9  3.7  0.5]


The PC1 and PC2 explains total of 95.9 % variation and we use these two again in above model.

But we dont know what we will drop or use, as the IVs are now unidentitfied as PCs.

In [28]:
# Import PCA
from sklearn.decomposition import PCA

# Create PCA instance: model
model = PCA(n_components = 2) # PC1 and PC2 will be used

# Apply the fit_transform method of model to grains: pca_features
x = model.fit_transform(samples_scaled)

#principal components or PCA features
x.shape

(150, 2)

In [29]:
#split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4, random_state=123)
#x here represents input features post PCA

In [30]:
#implement classification using KNN
from sklearn.neighbors import KNeighborsClassifier

#Gridsearchcv to tune the value of k along with cross validation
from sklearn.model_selection import GridSearchCV

#declare the dictionary of the hyperparameter to be tuned
parameters = {"n_neighbors": range(1, 50), "weights": ['uniform', 'distance']}#1 to 49

gridsearch = GridSearchCV(KNeighborsClassifier(), parameters, cv=5)
#simple cross validation, not repeated

gridsearch.fit(x_train, y_train)
#, "weights": ['uniform', 'distance']

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': range(1, 50),
                         'weights': ['uniform', 'distance']})

In [31]:
#using gridsearch model to make predictions on the test data
y_pred = gridsearch.predict(x_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        22
           1       0.78      0.88      0.82        16
           2       0.90      0.82      0.86        22

    accuracy                           0.90        60
   macro avg       0.89      0.90      0.89        60
weighted avg       0.90      0.90      0.90        60



The accuracy is lower but we check for overfit :

In [32]:
y_predtrain = gridsearch.predict(x_train)

print(confusion_matrix(y_train, y_predtrain))

print(classification_report(y_train, y_predtrain))

[[28  0  0]
 [ 0 30  4]
 [ 0  3 25]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        28
           1       0.91      0.88      0.90        34
           2       0.86      0.89      0.88        28

    accuracy                           0.92        90
   macro avg       0.92      0.93      0.92        90
weighted avg       0.92      0.92      0.92        90



**This model is overfitted, and we now will use uniform wt model with grid search (97%)**